"""Repository helpers for User + Profile."""
from __future__ import annotations

import re

from aiogram.types import User as TGUser
from sqlalchemy import select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession

from bot.models import Profile, User

# Device IDs are generated by the Lira app — accept lowercase hex / uuid-ish
# tokens, capped at the column length. Anything else is rejected so a
# malformed deep link can never poison the unique index.
_DEVICE_ID_RE = re.compile(r"^[A-Za-z0-9._-]{8,64}$")


def is_valid_device_id(raw: str) -> bool:
    return bool(_DEVICE_ID_RE.match(raw))


async def get_or_create_user(session: AsyncSession, tg_user: TGUser) -> User:
    """Look up by telegram_id and create row if missing.

    Race-safe: when several /start updates arrive at once Telegram may dispatch
    them concurrently; if two transactions both miss the SELECT they will both
    try to INSERT and one will hit the UNIQUE(telegram_id) constraint. We
    recover by rolling back the failed insert and re-fetching the row that the
    other transaction wrote.
    """
    stmt = select(User).where(User.telegram_id == tg_user.id)
    user = (await session.execute(stmt)).scalar_one_or_none()
    if user is None:
        user = User(
            telegram_id=tg_user.id,
            username=tg_user.username,
            first_name=tg_user.first_name,
            language_code=tg_user.language_code,
        )
        session.add(user)
        try:
            await session.flush()
        except IntegrityError:
            await session.rollback()
            user = (await session.execute(stmt)).scalar_one()
    if user is not None:
        user.username = tg_user.username
        user.first_name = tg_user.first_name
        user.language_code = tg_user.language_code
    return user


async def bind_device_id(
    session: AsyncSession, user: User, device_id: str
) -> bool:
    """Stamp the device id on the user, transferring it from any other
    user that previously claimed it. Returns True iff the column changed.

    The device id is unique across the table — when the same Lira install
    is re-linked to a different Telegram account, we re-point the row.
    """
    if not is_valid_device_id(device_id):
        return False
    if user.device_id == device_id:
        return False
    other_stmt = select(User).where(User.device_id == device_id)
    other = (await session.execute(other_stmt)).scalar_one_or_none()
    if other is not None and other.id != user.id:
        other.device_id = None
        await session.flush()
    user.device_id = device_id
    await session.flush()
    return True


async def get_or_create_profile(session: AsyncSession, user: User) -> Profile:
    stmt = select(Profile).where(Profile.user_id == user.id)
    profile = (await session.execute(stmt)).scalar_one_or_none()
    if profile is None:
        profile = Profile(user_id=user.id)
        session.add(profile)
        try:
            await session.flush()
        except IntegrityError:
            await session.rollback()
            profile = (await session.execute(stmt)).scalar_one()
    return profile
